- name: Create docker network for digitalocean
  community.docker.docker_network:
    name: "{{ docker_network_name }}"
    enable_ipv6: true
    ipam_config:
      - subnet: "{{ ansible_default_ipv6.address | ansible.utils.ipsubnet(digitalocean_v6_subnet) }}"
  when: cloud == "digitalocean"

- name: Create docker network for hetzner
  community.docker.docker_network:
    name: "{{ docker_network_name }}"
    enable_ipv6: true
    ipam_config:
      - subnet: "{{ ansible_default_ipv6.address | ansible.utils.ipsubnet(hetzner_v6_subnet) }}"
  when: cloud == "hetzner"

- name: Create docker network
  community.docker.docker_network:
    name: "{{ docker_network_name }}"
  when: cloud is not defined
