---

beaconchain_explorer_aio_user: beaconchainexplorer

beaconchain_explorer_aio_url_erigon: http://your-erigon-node:8545
beaconchain_explorer_aio_url_erigon_ws: ws://your-erigon-node:8545
beaconchain_explorer_aio_url_geth: http://your-geth-node:8545

beaconchain_explorer_aio_sql_init_file: files/postgres/tables.sql
beaconchain_explorer_aio_docker_compose_file: templates/docker-compose.yml.j2
beaconchain_explorer_aio_config_file: templates/config.yml.j2

beaconchain_explorer_aio_installation_dir: /opt/beaconchain-explorer-aio

beaconchain_explorer_aio_docker_image_default: gobitfly/eth2-beaconchain-explorer:v1.0.3
beaconchain_explorer_aio_docker_image_exporter: "{{ beaconchain_explorer_aio_docker_image_default }}"
beaconchain_explorer_aio_docker_image_eth1indexer: "{{ beaconchain_explorer_aio_docker_image_default }}"
beaconchain_explorer_aio_docker_image_statistics: "{{ beaconchain_explorer_aio_docker_image_default }}"
beaconchain_explorer_aio_docker_image_frontend: "{{ beaconchain_explorer_aio_docker_image_default }}"
beaconchain_explorer_aio_docker_image_frontend_updater: "{{ beaconchain_explorer_aio_docker_image_default }}"

beaconchain_explorer_aio_docker_image_redis: redis:7
beaconchain_explorer_aio_docker_image_postgres: postgres:14
beaconchain_explorer_aio_docker_image_bigtable: guybrush/explorer-workshop-bogota # TODO get an image with little_bigtable+cbt

beaconchain_explorer_aio_data_dir_explorer: /data/beaconchain-explorer-aio/explorer
beaconchain_explorer_aio_data_dir_postgres: /data/beaconchain-explorer-aio/postgres
beaconchain_explorer_aio_data_dir_bigtable: /data/beaconchain-explorer-aio/bigtable
beaconchain_explorer_aio_data_dir_redis: /data/beaconchain-explorer-aio/redis

beaconchain_explorer_aio_cmd_exporter:
  - /app/explorer
  - -config=/config.yml

beaconchain_explorer_aio_cmd_eth1indexer:
  - /app/eth1indexer
  - -bigtable.project=explorer
  - -bigtable.instance=bigtable:9000
  - -network=sepolia
  - "-erigon={{ beaconchain_explorer_aio_url_erigon_ws }}"
  - -data.concurrency=2
  - -data.offset=100
  - -data.start=0
  - -data.end=0
  - -blocks.concurrency=2
  - -blocks.offset=100
  - -blocks.start=0
  - -blocks.end=0
  - -balances.enabled
  - -balances.batch=100

beaconchain_explorer_aio_cmd_statistics:
  - /app/statistics
  - -config=/config.yml

beaconchain_explorer_aio_cmd_frontend_updater:
  - /app/frontend-data-updater
  - -config=/config.yml

beaconchain_explorer_aio_cmd_frontend:
  - /app/explorer
  - -config=/config.yml

# This can be used to create additional config files for the beaconchain explorer.
# It's useful when using private testnets and you need to mount a custom phase0/altair
# as the chain config. All files will be available within the explorer containers on the
# /configs directory.
beaconchain_explorer_aio_extra_config_files: {}
#
#  phase0.yml: |
#    # Extends the mainnet preset
#    PRESET_BASE: "gnosis"
#    # needs to exist because of Prysm. Otherwise it conflicts with mainnet genesis
#    CONFIG_NAME: "chiado"
