- name: Extract CL ENRs
  ansible.builtin.import_tasks: consensus_layer.yaml
  when: ethereum_node_fact_discovery_cl

- name: Extract EL enodes
  ansible.builtin.import_tasks: execution_layer.yaml
  when: ethereum_node_fact_discovery_el
