- name: Validate inputs
  ansible.builtin.import_tasks: validations.yaml

- name: Setup docker network
  ansible.builtin.include_role:
    name: ethpandaops.general.docker_network
  vars:
    docker_network_name: "{{ ethereum_node_docker_network_name }}"

- name: Cleanup clients that shouldn't be running
  ansible.builtin.import_tasks: cleanup.yaml

- name: Setup mev_boost
  ansible.builtin.include_role:
    name: ethpandaops.general.mev_boost
  vars:
    mev_boost_container_networks: "{{ ethereum_node_docker_networks }}"
  when: ethereum_node_mev_boost_enabled

- name: Setup json_rpc_snooper
  ansible.builtin.include_role:
    name: ethpandaops.general.json_rpc_snooper
  vars:
    json_rpc_snooper_container_networks: "{{ ethereum_node_docker_networks }}"
  when: ethereum_node_json_rpc_snooper_enabled

- name: Setup execution client
  ansible.builtin.import_tasks: setup_el.yaml
  when: ethereum_node_el_enabled

- name: Setup consensus client
  ansible.builtin.import_tasks: setup_cl.yaml
  when: ethereum_node_cl_enabled

- name: Collect and set facts about the nodes
  ansible.builtin.include_role:
    name: ethpandaops.general.ethereum_node_fact_discovery
    apply:
      tags:
        - ethereum_node_fact_discovery
  tags:
    - ethereum_node_fact_discovery
  vars:
    ethereum_node_fact_discovery_el: "{{ ethereum_node_el_enabled }}"
    ethereum_node_fact_discovery_cl: "{{ ethereum_node_cl_enabled }}"
  when: ethereum_node_fact_discovery_enabled

- name: Setup metrics exporter
  ansible.builtin.include_role:
    name: ethpandaops.general.ethereum_metrics_exporter
  vars:
    ethereum_metrics_exporter_el_endpoint: "{{ ethereum_node_el_rpc_endpoint }}"
    ethereum_metrics_exporter_cl_endpoint: "{{ ethereum_node_cl_beacon_endpoint }}"
    ethereum_metrics_exporter_container_networks: "{{ ethereum_node_docker_networks }}"
  when: ethereum_node_metrics_exporter_enabled

- name: Setup xatu sentry
  ansible.builtin.include_role:
    name: ethpandaops.general.xatu_sentry
  vars:
    xatu_sentry_config_beacon_uri: "{{ ethereum_node_cl_beacon_endpoint }}"
    xatu_sentry_container_networks: "{{ ethereum_node_docker_networks }}"
  when: ethereum_node_xatu_sentry_enabled
