- name: "Execution client: besu"
  when: ethereum_node_el == "besu"
  ansible.builtin.include_role:
    name: ethpandaops.general.besu
  vars:
    besu_ports_p2p: "{{ ethereum_node_el_ports_p2p_tcp }}"
    besu_ports_http_rpc: "{{ ethereum_node_el_ports_http_rpc }}"
    besu_ports_engine: "{{ ethereum_node_el_ports_engine }}"
    besu_ports_metrics: "{{ ethereum_node_el_ports_metrics }}"
    besu_container_networks: "{{ ethereum_node_docker_networks }}"

- name: "Execution client: geth"
  when: ethereum_node_el == "geth"
  ansible.builtin.include_role:
    name: ethpandaops.general.geth
  vars:
    geth_ports_p2p: "{{ ethereum_node_el_ports_p2p_tcp }}"
    geth_ports_http_rpc: "{{ ethereum_node_el_ports_http_rpc }}"
    geth_ports_engine: "{{ ethereum_node_el_ports_engine }}"
    geth_ports_metrics: "{{ ethereum_node_el_ports_metrics }}"
    geth_container_networks: "{{ ethereum_node_docker_networks }}"

- name: "Execution client: erigon"
  when: ethereum_node_el == "erigon"
  ansible.builtin.include_role:
    name: ethpandaops.general.erigon
  vars:
    erigon_ports_p2p: "{{ ethereum_node_el_ports_p2p_tcp }}"
    erigon_ports_http_rpc: "{{ ethereum_node_el_ports_http_rpc }}"
    erigon_ports_engine: "{{ ethereum_node_el_ports_engine }}"
    erigon_ports_metrics: "{{ ethereum_node_el_ports_metrics }}"
    erigon_container_networks: "{{ ethereum_node_docker_networks }}"

- name: "Execution client: nethermind"
  when: ethereum_node_el == "nethermind"
  ansible.builtin.include_role:
    name: ethpandaops.general.nethermind
  vars:
    nethermind_ports_p2p: "{{ ethereum_node_el_ports_p2p_tcp }}"
    nethermind_ports_http_rpc: "{{ ethereum_node_el_ports_http_rpc }}"
    nethermind_ports_engine: "{{ ethereum_node_el_ports_engine }}"
    nethermind_ports_metrics: "{{ ethereum_node_el_ports_metrics }}"
    nethermind_container_networks: "{{ ethereum_node_docker_networks }}"
